name: Convert Project Markdown to HTML

on:
  push:
    branches:
      - main
    paths:
      - 'projects/*.md'

jobs:
  convert-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Debug and Convert
        run: |
          echo "=== DEBUG INFO ==="
          ls -la projects/
          echo "Files found:"
          find projects/ -name "*.md" -type f
          
          mkdir -p project-pages
          
          for file in projects/*.md; do
            echo "Processing: $file"
            if [ ! -f "$file" ]; then
              echo "File does not exist: $file"
              continue
            fi
            
            filename=$(basename "$file" .md)
            echo "Filename: $filename"
            
            # Simple extraction
            title=$(grep "^title:" "$file" | sed 's/title: //')
            id=$(grep "^id:" "$file" | sed 's/id: //')
            image=$(grep "^image:" "$file" | sed 's/image: //')
            url=$(grep "^url:" "$file" | sed 's/url: //')
            
            echo "Extracted - Title: $title, ID: $id"
            
            # Create HTML
            cat > "project-pages/${filename}.html" << EOF
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>${title} - My Portfolio</title>
              <link rel="stylesheet" href="../styles.css">
          </head>
          <body>
              <header>
                  <h1>${title}</h1>
              </header>
              <div class="container">
                  <a href="../index.html" class="back-link">← Back to Portfolio</a>
                  <div class="project-detail">
                      <img src="../${image}" alt="${title}">
                      <div class="content">
          EOF
                      
                      # Convert markdown content with Pandoc (skip frontmatter)
                      awk '/^---$/{f++} f==2{print}' "$file" | pandoc -f markdown -t html >> "project-pages/${filename}.html"
                      
                      cat >> "project-pages/${filename}.html" << EOF
                      </div>
                      <p><a href="${url}" target="_blank">View Project</a></p>
                  </div>
              </div>
              <footer>
                  <p>Connect with me on <a href="https://linkedin.com/in/your-profile" target="_blank">LinkedIn</a></p>
              </footer>
          </body>
          </html>
          EOF
            
            echo "Created: project-pages/${filename}.html"
          done
          
          echo "=== GENERATED FILES ==="
          ls -la project-pages/

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Convert MD to HTML" || echo "No changes"
          git push